-- English Premier League related microposts (300 entries)

-- Team-related posts
INSERT INTO microposts (content, user_id, created_at, updated_at) VALUES 
('Manchester City''s new season is starting! Can they achieve consecutive league titles this year?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Liverpool''s attacking lineup is fantastic! Salah''s goal was absolutely artistic', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Arsenal''s young players are showing remarkable growth. This season looks promising', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Chelsea''s new manager''s tactics are intriguing! Excited to see what changes they bring', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Manchester United''s traditional style is making a comeback', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Tottenham''s attacking football is so entertaining! Kane is in great form', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Newcastle''s promotion battle is going to be intense. The fans'' passion is incredible', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Aston Villa''s midfield combination is exquisite! Today''s match was brilliant', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('West Ham''s solid defense shines! This season they could aim for European competition', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Brighton''s beautiful passing game is mesmerizing! The young players have such high technical ability', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Player-related posts
('Harry Kane''s goal-scoring instinct is truly wonderful. One of the Premier League''s best strikers', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Mohamed Salah''s dribbling and shooting technique are world-class', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Kevin De Bruyne''s passing vision never fails to amaze me', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Virgil van Dijk''s defending is incredibly stable! Liverpool''s pillar', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Raheem Sterling''s pace and finishing ability are threatening', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Bruno Fernandes'' free kicks are artistic! Man United''s savior', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Son Heung-min''s shots with both feet are magnificent. Korea''s pride!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Jack Grealish''s individual skills and creativity are inspiring', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Diogo Jota''s scoring ability supports Liverpool''s strength', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Mason Mount''s playmaking in midfield is brilliant', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Match result posts
('Manchester City vs Liverpool was this season''s best match!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Arsenal 3-2 Chelsea, the match was unpredictable until the very end', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Tottenham vs Manchester United was an epic battle! Both teams were fantastic', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Today''s North London Derby had me on the edge of my seat', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Manchester Derby''s intensity comes through even on screen!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Liverpool vs Everton Merseyside Derby is a must-watch', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('West Ham vs Chelsea was a close game! Victory decided at the very last moment', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Aston Villa''s comeback was emotional! Their never-give-up spirit is wonderful', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Brighton''s solid defense to counter-attack was executed perfectly', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('This season''s Premier League is unpredictable! Every team is strong', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Tactics and manager posts
('Pep Guardiola''s tactics evolve every time. Genius manager', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Jurgen Klopp''s gegenpressing makes perfect sense', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Arteta''s Arsenal plays beautiful football', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Conte''s 3-5-2 system fits Chelsea perfectly', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Ole Gunnar Solskjaer''s attacking approach is paying off', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Mourinho''s defensive tactics remain solid as ever', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Bruce''s Newcastle shows organized defending', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Potter''s Brighton plays creative football that''s captivating', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Moyes'' West Ham has excellent balanced team building', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Gerrard''s Aston Villa has an attractive attacking style', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Transfer and news posts
('This summer''s transfer window is active! Looking forward to each team''s reinforcements', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Curious to see how the new signings will perform', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The emergence of young players is energizing the Premier League', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Veteran players'' experience is valuable treasure for teams', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s international nature is one of its charms. Talent from around the world', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Academy graduates'' success is a great pride for each club', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Wishing injured players a speedy recovery. Health comes first!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('VAR decisions spark debate but are necessary for fair judgment', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s level is world''s best! Every match is worth watching', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Fan passion makes the Premier League special', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Stadium and atmosphere posts
('Old Trafford''s atmosphere is exceptional! The home of the Red Devils', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The beautiful pitch at Emirates Stadium is mesmerizing to watch', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Etihad Stadium''s sky blue supporters'' cheering is spectacular', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Anfield''s You''ll Never Walk Alone gives me goosebumps', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Stamford Bridge''s historic presence is beautiful', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Tottenham Hotspur Stadium''s state-of-the-art facilities are amazing', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('West Ham''s matches at London Stadium are full of excitement', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Villa Park''s traditional atmosphere is lovely', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Everton supporters at Goodison Park are the best', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Newcastle fans'' passion at St. James'' Park is incredible', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- History and legends posts
('The legends who colored Premier League history will be remembered forever', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Ferguson''s Manchester United era was legendary', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Arsenal''s unbeaten season ''The Invincibles'' is the greatest record ever', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Liverpool''s Miracle of Istanbul was so moving', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Leicester City''s miraculous title win was like a dream', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Cristiano Ronaldo''s Manchester United days were brilliant', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Thierry Henry''s play at Arsenal was artistic', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Frank Lampard vs Steven Gerrard midfield battles were classic', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Alan Shearer''s goal record still hasn''t been broken', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Ryan Giggs'' left-wing runs were beautiful', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Match viewing and experience posts
('Watching games at the stadium is extraordinary! Completely different from TV', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Planning a UK trip to watch Premier League matches', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Supporting with fellow fans at the pub was the best experience', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Wearing scarves and jerseys while supporting is so much fun', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Even for early morning kickoffs, I wake up to watch!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League discussions with friends can go on for hours', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Collecting merchandise from my favorite team is my hobby', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('I watch Premier League highlights over and over again', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('My love for the team I''ve supported since childhood never changes', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League makes weekends exciting!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Prediction and analysis posts
('This season''s title race will be fierce! Four teams neck and neck', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Top 4 race is intense! Which team will secure European qualification?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Relegation battle is captivating too. Which teams can stay up?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Golden Boot race is exciting! Who will score over 30 goals this year?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Playmaker of the Year is also interesting. Expecting creative players to shine', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Clean sheet numbers show goalkeeper quality. Who will be the best GK?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Young Player of the Year candidates are abundant! Who''s the future star?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Manager of the Year is competitive! Which manager''s tactics will be recognized?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Excited about January transfer window surprises', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Predicting final table positions is so enjoyable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Japanese players posts
('Japanese players'' success in Premier League makes me proud!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Takumi Minamino''s technique and speed are world-class', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Takehiro Tomiyasu''s defensive ability supports Arsenal', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Kaoru Mitoma''s dribbling runs are thrilling to watch', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Wataru Endo''s presence in midfield is impressive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Seeing Japanese players succeed in Premier League makes me happy', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Excited about Daichi Kamada''s Chelsea move! What impact will he make?', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Looking forward to Ko Itakura''s growth. Hope he becomes a national team regular', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Having Japan national team stars playing in Premier League is reassuring', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Hope more Japanese players succeed in Premier League', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- VAR and referee posts
('VAR decisions are controversial but necessary technology for fairness', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Referees'' judgment and communication skills are excellent', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Offside decisions have become stricter and more fair', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Penalty decisions always spark debate', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Hope red card criteria become more consistent', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Assistant referees'' flag timing is crucial', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Should keep criticism of referees moderate after matches', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Happy to see more female referees getting opportunities', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Referees'' physical condition is also an important factor', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Human errors are understandable. Technology provides support', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Fantasy Football posts
('Fantasy Premier League gave me good points this week!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Captain selection is the most important in Fantasy', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Getting high points with cheap players is Fantasy''s charm', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Planning team selection while checking fixtures is fun', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Checking injury list is essential', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Identifying rotation players is difficult', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Targeting clean sheet bonus with defenders', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Goalkeeper selection should be done carefully', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Free hit card timing is important', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Competing with friends in mini-leagues is fun', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- International matches and national teams posts
('Looking forward to Premier League players'' performances in international matches', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League players shined at the World Cup', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('England''s good performance at Euro deserves praise', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Worried about injuries in international matches. Want to see club performances too', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Players'' attitude of not taking international friendlies lightly is wonderful', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('How national team tactics influence club teams is interesting', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Young players'' first national team call-ups are emotional', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Veteran players'' international retirement is sad but hopeful for youth', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League players'' performances at Copa America are unmissable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Africa Cup of Nations is also a tournament to watch', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Media and broadcasting posts
('Premier League commentators'' observations are always accurate', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Sky Sports broadcast quality is high', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Half-time analysis helps deepen match understanding', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Player interviews reveal their personalities', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Manager press conferences help understand tactics', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s official YouTube channel is comprehensive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Match of the Day is one of weekend''s pleasures', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Players'' social media posts are interesting', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Documentary programs showing club''s behind-the-scenes are valuable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Slow-motion replay footage shows technical excellence', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Stats and data posts
('xG (Expected Goals) numbers help match analysis', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Players with over 90% pass accuracy are exceptional', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Sprint count and heat maps tell the story of player''s work rate', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Players with high duel win rate are reliable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Correlation between cross success and chance creation is interesting', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Tackle success rate and interception numbers show defensive ability', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Possession percentage alone doesn''t determine match superiority', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Shot quality matters more than shot quantity', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Offside count can also indicate tactical understanding', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Advances in data analysis make football more enjoyable to understand', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Final additional posts to reach 300
('Premier League''s appeal is endless! Each season brings new emotions', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Want to show respect to players competing in the world''s best league', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League teaches us the beauty of football', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Will continue supporting Premier League forever!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Thank you for another wonderful match, Premier League!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Can''t wait for next week''s matches!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League made me fall in love with football', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Watching Premier League with friends and family is the best time', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Moved by Premier League''s history and tradition', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Excited to see what the next generation of players will show us', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Additional posts to complete 300
('The intensity of Premier League matches is unmatched worldwide', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Every Premier League weekend brings new surprises and drama', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The tactical evolution in Premier League is fascinating to follow', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League goalkeepers have reached incredible levels of skill', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The physicality and pace of Premier League is breathtaking', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s global reach makes it truly special', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Youth development in Premier League clubs is impressive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The competitiveness from top to bottom makes every match crucial', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League set pieces have become works of art', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The depth of squad in Premier League teams is remarkable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- Final 30 posts
('Multi-cultural nature of Premier League enriches the game', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League managers'' press conferences are always insightful', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The tradition and innovation balance in Premier League is perfect', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s Christmas fixture list is always exciting', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The role of captains in Premier League teams is crucial', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s environmental initiatives are commendable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Community work by Premier League clubs makes a real difference', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The mental strength required in Premier League is immense', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s influence on world football continues to grow', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The unpredictability of Premier League keeps fans on edge', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s production quality sets the standard globally', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The respect between players and officials in Premier League is admirable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s accessibility across different platforms is excellent', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The coaching evolution in Premier League is remarkable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League players'' dedication to fitness is inspiring', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The storytelling aspect of Premier League seasons is captivating', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s impact on local communities is significant', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The scientific approach to training in Premier League is advanced', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s charity work deserves more recognition', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The psychological pressure in Premier League shapes true champions', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s winter schedule tests teams'' true depth', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The medical teams in Premier League clubs work miracles', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s anti-discrimination efforts are important', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The business model of Premier League clubs is fascinating', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s contribution to England''s economy is massive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The referee development in Premier League sets global standards', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s digital innovation enhances fan experience', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The educational programs by Premier League clubs inspire youth', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s legacy will inspire generations of footballers', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Grateful for all the memories Premier League has given us!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW());
