-- Additional 100 Premier League related microposts

INSERT INTO microposts (content, user_id, created_at, updated_at) VALUES 
('The atmosphere at Wembley during England matches is electric!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s social media presence keeps fans engaged globally', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The transfer deadline day drama never gets old!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League music and anthems give me chills every time', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The dedication of Premier League groundskeepers is incredible', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Watching Premier League in different time zones around the world', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League Hall of Fame celebrates true legends', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Technology in Premier League has revolutionized the game', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s commitment to grassroots football is admirable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League trophy is one of the most beautiful in sport', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Loan system in Premier League helps young players develop', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s pandemic response showed great resilience', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The rivalries in Premier League add extra spice to matches', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s global ambassadors spread the game beautifully', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League official app keeps me updated constantly', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Financial Fair Play regulations help maintain competitive balance', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for mental health awareness is vital', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Watching Premier League matches in 4K is a visual treat', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s climate action initiatives are progressive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Former Premier League players make excellent pundits', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s injury time calculations have become more accurate', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s partnerships with local schools inspire kids', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s official podcast provides great insights', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Watching Premier League on mobile while commuting is perfect', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s equality and diversity campaigns matter', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s referee mic''d up sessions are fascinating', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for women''s football is growing', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League clubs'' training ground facilities are world-class', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s concussion protocols prioritize player safety', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s official statistics website is incredibly detailed', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s community shield marks the season start', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League matches being carbon neutral would be amazing', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s anti-piracy efforts protect the product', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for disabled fans is commendable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s official merchandise quality has improved', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s partnerships with betting companies spark debate', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for LGBTQ+ inclusion is important', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s artificial intelligence use in analysis is cutting-edge', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for ex-players'' welfare is crucial', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s virtual reality experiences bring fans closer', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s academic partnerships advance sports science', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for referee education is ongoing', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s emergency fund helped clubs during COVID', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s data sharing with coaches improves performance', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s commitment to fan experience keeps evolving', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s influence on global football economics is massive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for local food banks is heartwarming', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s investment in youth coaching pays dividends', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s transparency in decision-making has improved', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for retired players'' health is vital', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s innovation in stadium design is impressive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s collaboration with universities advances research', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for coaching diversity is progressive', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s investment in pitch technology ensures quality', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for fan safety is paramount', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s education programs teach values beyond football', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s global licensing deals spread the brand', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for local journalism helps coverage', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s commitment to fair competition never wavers', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s investment in referee technology improves accuracy', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for military personnel is admirable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s partnerships with charities make real impact', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s digital transformation enhances everything', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for sustainable transport to games', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s heritage and tradition remain intact', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for mental health in football is crucial', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s global appeal transcends cultural boundaries', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s investment in data analytics changes everything', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s commitment to excellence never stops', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for healthy lifestyles inspires millions', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s legacy will continue for generations', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s innovation in broadcasting sets global standards', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for education through sport is valuable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s commitment to accessibility ensures inclusion', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s influence on youth development is profound', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for community initiatives builds bridges', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s commitment to integrity guides every decision', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s investment in security ensures safe experiences', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s global partnerships expand opportunities', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for innovation drives progress forward', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s commitment to quality never compromises', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s influence on sports psychology is significant', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for equality creates positive change', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s investment in infrastructure benefits everyone', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s commitment to sustainability is commendable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for cultural diversity enriches the game', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s global impact extends far beyond football', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s commitment to continuous improvement inspires all', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s dedication to fans remains unwavering', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for health and wellbeing matters deeply', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s commitment to transparency builds trust', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s investment in technology enhances every aspect', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s support for social causes makes a difference', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s commitment to development creates opportunities', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s influence on global sports is undeniable', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s support for personal growth through sport is inspiring', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League''s legacy of excellence continues to grow', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League''s commitment to the future of football is absolute', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('The Premier League will always hold a special place in our hearts', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Premier League: where dreams come true and legends are born!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('Long live the Premier League - the greatest show on earth!', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW());
