-- プレミアリーグ関連の300件のmicropostを挿入するSQLスクリプト

-- チーム情報
INSERT INTO microposts (content, user_id, created_at, updated_at) VALUES 
('マンチェスター・シティの新シーズンが始まる！今年こそリーグ連覇なるか？', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('リヴァプールの攻撃陣が素晴らしい！サラーのゴールは芸術的だった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アーセナルの若手選手たちの成長が著しい。今シーズンは期待できそう', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('チェルシーの新監督の戦術に注目！どんな変化を見せるか楽しみ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('マンチェスター・ユナイテッドの伝統的なスタイルが復活してきている', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('トッテナムの攻撃的なサッカーは見ていて楽しい！ケインの調子も上々', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ニューカッスルの昇格争いは熾烈になりそう。サポーターの熱気がすごい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アストン・ヴィラの中盤の組み合わせが絶妙！今日の試合は素晴らしかった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ウェストハムの堅守が光る！今シーズンはヨーロッパの舞台も狙える', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ブライトンの美しいパスワークに感動！若い選手たちの技術が高い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 選手に関する投稿
('ハリー・ケインのゴール感覚は本当に素晴らしい。プレミアリーグ最高のストライカーの一人', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('モハメド・サラーのドリブルとシュートの技術は世界トップクラス', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ケビン・デ・ブルイネのパスセンスに毎回驚かされる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ヴィルヒル・ファン・ダイクの守備は安定感抜群！リヴァプールの柱', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ラヒーム・スターリングの速さと決定力は脅威的', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ブルーノ・フェルナンデスのFKは芸術的！マンUの救世主', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ソン・フンミンの両足からのシュートは素晴らしい。韓国の誇り！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ジャック・グリーリッシュの個人技とクリエイティビティに感動', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ディオゴ・ジョタの得点力がリヴァプールの強さを支えている', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('マソン・マウントの中盤でのプレーメーキングが光る', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 試合結果に関する投稿
('マンチェスター・シティ vs リヴァプールの試合は今シーズンベストマッチ！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アーセナル 3-2 チェルシー、最後まで分からない試合展開だった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('トッテナム vs マンチェスター・ユナイテッドの激闘！両チーム素晴らしかった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('今日のノース・ロンドン・ダービーは手に汗握る展開だった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('マンチェスター・ダービーの熱気は画面越しでも伝わってくる！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('リヴァプール vs エヴァートンのマージーサイド・ダービーは必見', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ウェストハム vs チェルシーの接戦！最後の最後で決着がついた', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アストン・ヴィラの逆転劇に感動！諦めない精神が素晴らしい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ブライトンの堅実な守備からのカウンターが見事に決まった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('今シーズンのプレミアリーグは予想がつかない！どのチームも強い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 戦術・監督に関する投稿
('ペップ・グアルディオラの戦術は毎回進化している。天才的な監督', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ユルゲン・クロップのゲーゲンプレッシングは理にかなっている', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アルテタのアーセナルは美しいサッカーを展開している', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('コンテの3-5-2システムがチェルシーにフィットしている', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('オーレ・グンナー・スールシャーの攻撃的な采配が功を奏している', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('モウリーニョの守備戦術は相変わらず堅実', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ブルース監督のニューカッスルは組織的な守備が光る', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ポッターのブライトンは創造性あふれるサッカーで魅力的', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('モイーズのウェストハムはバランスの取れたチーム作りが素晴らしい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ジェラードのアストン・ヴィラは攻撃的なスタイルが魅力的', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 移籍・ニュースに関する投稿
('今夏の移籍市場は活発！各チームの補強が楽しみ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('新加入選手たちがどのような活躍を見せるか注目', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('若手選手の台頭がプレミアリーグを盛り上げている', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ベテラン選手の経験値がチームにとって貴重な財産', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグの国際性が魅力の一つ。世界中から才能が集結', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アカデミー出身選手の活躍は各クラブにとって大きな誇り', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('負傷選手の早期復帰を願っています。健康第一！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('VARの判定は議論を呼ぶが、公正なジャッジのために必要', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグのレベルの高さは世界一！毎試合が見応え十分', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ファンの情熱がプレミアリーグを特別なものにしている', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- スタジアム・雰囲気に関する投稿
('オールド・トラッフォードの雰囲気は格別！赤い悪魔の聖地', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('エミレーツ・スタジアムの美しい芝生でのプレーは見惚れる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('エティハド・スタジアムのスカイブルーサポーターの声援が圧巻', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アンフィールドのYou\'ll Never Walk Aloneは鳥肌もの', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('スタンフォード・ブリッジの歴史を感じる佇まいが素敵', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('トッテナム・ホットスパー・スタジアムの最新設備に驚き', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ロンドン・スタジアムでのウェストハムの試合は迫力満点', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ヴィラ・パークの伝統的な雰囲気が大好き', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('グディソン・パークのエヴァートンサポーターは最高', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('セント・ジェームズ・パークのニューカッスルファンの熱気は凄い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 歴史・レジェンドに関する投稿
('プレミアリーグの歴史を彩るレジェンドたちの功績は永遠', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ファーガソン監督時代のマンUの強さは伝説的', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アーセナルの無敗優勝「インヴィンシブルズ」は史上最高の記録', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('リヴァプールのイスタンブールの奇跡は感動的だった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('レスター・シティの奇跡的な優勝は夢のような出来事', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('クリスティアーノ・ロナウドのマンU時代は輝いていた', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ティエリ・アンリのアーセナルでのプレーは芸術的', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('フランク・ランパードとスティーブン・ジェラードの中盤対決は名勝負', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アラン・シアラーのゴール記録は今でも破られていない', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ライアン・ギグスの左サイドからの突破は美しかった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 試合観戦・体験に関する投稿
('スタジアムで観戦する試合の迫力は格別！テレビとは全然違う', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグ観戦のためにイギリス旅行を計画中', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('パブでサポーターと一緒に応援する体験は最高だった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('スカーフとユニフォームを着て応援するのは楽しい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('早朝のキックオフでも頑張って起きて観戦！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('友達とのプレミアリーグ談義は何時間でも続けられる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('お気に入りのチームのグッズをコレクションするのが趣味', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグのハイライト映像を何度も見返している', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('子供の頃から応援しているチームへの愛は変わらない', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグがあるから週末が楽しみ！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 予想・分析に関する投稿
('今シーズンの優勝争いは激戦になりそう！4チームが横一線', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('トップ4争いが熾烈！ヨーロッパの切符を手にするのはどのチーム？', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('降格争いも目が離せない。どのチームが残留できるか', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('得点王争いも注目！今年は誰が30ゴールを超えるか', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アシスト王の行方も気になる。クリエイティブな選手の活躍に期待', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('クリーンシート数でGKの評価も分かる。誰が最優秀GKになる？', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('若手最優秀選手賞の候補が豊富！未来のスターは誰？', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('年間最優秀監督は激戦！どの監督の戦術が評価される？', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('1月の移籍市場でどんなサプライズがあるか楽しみ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('シーズン終了時の各チームの順位を予想するのが楽しい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 日本人選手に関する投稿
('日本人選手のプレミアリーグでの活躍が誇らしい！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('南野拓実のテクニックとスピードは世界レベル', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('冨安健洋の守備力がアーセナルを支えている', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('三笘薫のドリブル突破は見ていてワクワクする', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('遠藤航の中盤での存在感が光る', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('日本人選手がプレミアで成功する姿を見ると嬉しくなる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('鎌田大地のチェルシー移籍に期待！どんな活躍を見せる？', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('板倉滉の成長が楽しみ。代表でも中心選手になってほしい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('日本代表の主力がプレミアでプレーしているのは心強い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('これからも多くの日本人選手がプレミアで活躍してほしい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- VAR・審判に関する投稿
('VARの判定には賛否両論あるが、公正性のために必要な技術', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('主審の判断力とコミュニケーション能力は素晴らしい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('オフサイドの判定が厳格になってより公正になった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ペナルティーキックの判定は毎回議論を呼ぶ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('レッドカードの基準が統一されることを望む', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('副審の旗を上げるタイミングが重要', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('試合後の審判への批判は控えめにしたい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('女性審判の活躍も増えてきて嬉しい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('審判のフィジカルコンディションも重要な要素', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('誤審も人間だから仕方ない。テクノロジーでサポート', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- ファンタジーフットボールに関する投稿
('ファンタジープレミアリーグで今週はポイントを稼げた！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('キャプテン選びがファンタジーで最も重要', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('安い選手で高ポイントを取るのがファンタジーの醍醐味', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('フィクスチャーを見ながらチーム編成を考えるのが楽しい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('負傷者リストをチェックするのは欠かせない', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ローテーション選手の見極めが難しい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ディフェンダーでクリーンシートボーナスを狙う', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ゴールキーパー選びは慎重に行いたい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('フリーヒットカードの使うタイミングが重要', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('友達とのミニリーグで競い合うのが面白い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 国際試合・代表チームに関する投稿
('プレミア選手の代表戦での活躍も楽しみ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ワールドカップでのプレミア選手の活躍が光った', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ユーロでのイングランド代表の健闘を称えたい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('代表戦での負傷が心配。クラブでの活躍も見たい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('国際親善試合でも手を抜かない選手の姿勢が素晴らしい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('各国代表の戦術がクラブチームに与える影響も興味深い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('若い選手の代表初選出は感動的', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ベテラン選手の代表引退は寂しいが、若手に期待', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('コパ・アメリカでのプレミア選手の活躍も見逃せない', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('アフリカ・ネイションズカップも要注目の大会', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- メディア・放送に関する投稿
('プレミアリーグの解説者のコメントがいつも的確', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('スカイスポーツの中継はクオリティが高い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ハーフタイム分析が試合理解を深めてくれる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('選手インタビューから人柄が伝わってくる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('監督の記者会見も戦術理解に役立つ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグの公式YouTubeチャンネルが充実', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('マッチオブザデイは週末の楽しみの一つ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ソーシャルメディアでの選手の発信も面白い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ドキュメンタリー番組でクラブの裏側が見られるのは貴重', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('リプレイ映像のスローモーションで技術の高さが分かる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- スタッツ・データに関する投稿
('xG（期待得点）の数値が試合分析に役立つ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('パス成功率90%超えの選手は別格', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('スプリント数とヒートマップが選手の運動量を物語る', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('デュエル勝率の高い選手は頼りになる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('クロス成功数とチャンス創出数の相関が興味深い', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('タックル成功率とインターセプト数で守備力が分かる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('ボール保持率だけでは試合の優劣は決まらない', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('シュート数よりもシュートの質が重要', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('オフサイド回数も戦術理解度の指標になる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('データ分析の進歩がサッカーをより深く楽しませてくれる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),

-- 最終的な追加投稿で300件に到達
('プレミアリーグの魅力は尽きない！毎シーズン新たな感動がある', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('世界最高峰のリーグで戦う選手たちに敬意を表したい', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('サッカーの素晴らしさをプレミアリーグが教えてくれる', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('これからもプレミアリーグを応援し続けたい！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('今日も素晴らしい試合をありがとう、プレミアリーグ！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('来週の試合も楽しみで仕方がない！', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグがあるからサッカーが好きになった', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('友達や家族とプレミアリーグを見るのが最高の時間', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('プレミアリーグの歴史と伝統に感動', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW()),
('次世代の選手たちがどんな活躍を見せるか楽しみ', 1 + floor(random() * 101), NOW() - INTERVAL '1 day' * floor(random() * 30), NOW());
